### ISSUE TITLE
Extending this code to other apis

### ISSUE THREAD

**Issue by Racro** [hadiamjad/Not.js#1]
Hi,
I want to extend this codebase to cover other APIs. Though I get the logic to write additional hooks in `inject.js`, I do not understand the addBreakPoints function in `sele-hook.py` as it has hardcoded line numbers. What does that mean? 
Also, I don't find any hooks for `Touch` API.

**Comment by hadiamjad** [comment]
So we first run `sele.py` to identify the functions we want to place hooks. As paper mentions we only intereseted in api calls made by  functions present in " tracking or non-tracking request call stack". `sele.py` captures these request call stacks in the request.json file. In `sele-hook.py` we just put breakpoints for the request call stack functions r.f https://github.com/hadiamjad/Not.js/blob/88969a0ce216c941efdd71de0bea7e2e6e3a945e/sele-hook.py#L75. Harded coded are to make sure extension does not crash, so you can ignore but eventually `arr` is set in the breakpoints.json file for extension to read. Moreover, Touch.force uses addEventListener function `https://developer.mozilla.org/en-US/docs/Web/API/Touch/force`  which is already overriden in` inject.js`.

**Comment by hadiamjad** [comment]
Feel free to reach out on hadiamjad@vt.edu and we can schedule a call to help you with this and explain it better.
